services:
  - type: web
    name: al-chat-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

  - type: web
    name: al-chat-admin
    env: static
    plan: free
    buildCommand: cd admin-panel && npm install && npm run build
    staticPublishPath: admin-panel/dist
    envVars:
      - key: VITE_API_URL
        value: https://al-chat-backend-9xo5.onrender.com
