name: al_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  url_launcher: ^6.2.0
  flutter_webrtc: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
