name: al_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Networking & Async
  dio: ^5.0.0
  web_socket_channel: ^2.4.0
  
  # State Management
  provider: ^6.0.0
  
  # Storage & Utils
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  intl: ^0.18.0
  path: ^1.8.3
  url_launcher: ^6.1.11
  uni_links: ^0.5.1
  
  # Media
  image_picker: ^0.8.7
  
  # Firebase
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
