name: al_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.7
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.3.0
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  uuid: ^3.0.7
  intl: ^0.18.0
  path: ^1.8.3
  url_launcher: ^6.1.11
  uni_links: ^0.5.1
  flutter_webrtc: ^0.9.24
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
